# Generated by Django 4.0.3 on 2024-05-27 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzfinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='adress',
            field=models.TextField(),
        ),
    ]
