# Generated by Django 4.0.3 on 2024-05-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzfinder', '0002_alter_restaurant_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='adress',
            field=models.TimeField(),
        ),
    ]
