# Generated by Django 4.0.3 on 2024-05-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mzfinder', '0007_restaurant_imgsrc_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='adress',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='callNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='imgSrc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
